env: order-dev32434344444
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/pm208?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      force-response: true
#eureka:
#  client:
 #   service-url:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 9090
