dev: order-dev
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/pm208?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      force-response: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  http:
    encoding:
      force-response: true
server:
  port: 9090

  rabbitmq:
    host: 192.168.0.116
    username: guest
    password: guest
    port: 5672
