env: product-dev2
#server:
#  port: 8088
# eureka:
#  client:
 #   service-url:
   #   defaultZone: http://localhost:8762/eureka/
spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/pm208?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      force-response: true
  rabbitmq:
    host: 192.168.0.108
    password: guest
    port: 5672
    username: guest
